[tool.poetry]
name = "nshm2022db"
version = "0.1.0"
description = "Fault database for the GNS National Seismic Hazard Model."
authors = ["QuakeCoRE"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
numpy = "*"
qcore = { git = "https://github.com/ucgmsim/qcore" }
typer = "*"

[tool.poetry.group.dev.dependencies]
python-lsp-server = "*"
python-lsp-black = "*"
python-lsp-isort = "*"
black = "*"
rope = "*"
pyflakes = "*"
mccabe = "*"
pycodestyle = "*"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
